### PR TITLE
fix(cypress): add cypress overrides for printLength 

### PR DESCRIPTION
**Pull request by alhugot-emr**

### CODE REVIEW

**Review by clion-emr — APPROVED** [review]

**Review by clion-emr — DISMISSED** [review]
Prettier config seems ok

**Review by clion-emr — APPROVED** [review]
150 / 180 it is all fine.
Anyway it is difficult to say which one is the better config.

**Comment by alhugot-emr** [comment]
ok

**Review by clion-emr — APPROVED** [review]
re-approve

**Review by bsegault — APPROVED** [review]

**Pull request merged**
